sales_admin/applications/warehouse/urls.py
from django.urls import path
from . import views

app_name = "warehouse"

urlpatterns = [
    path("", views.index, name = "home_warehouse"),
    # URL para categorías de producto
    path("categorias-producto",views.product_category_list, name = "product_category_list"),
    path("categorias-producto/<int:product_category_id>",views.detail, name = "product_category_detail"),
    path("categorias-producto/nuevo", views.new, name="product_category_new"),
    path("categorias-producto/buscar", views.search,name="product_category_search"),
    path("categorias-producto/guardar", views.save, name="product_category_save")
]

sales_admin/sales_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('almacen/', include("applications.warehouse.urls")),
    path('api/warehouse/', include("applications.warehouse.api.urls")),
    path('api/login/', views.obtain_auth_token)
]

sales_admin/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        <main>
            {% block content%} {% endblock %}
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

sales_admin/templates/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            {% load static %}
            <img src="{% static 'images/icon_store.png'%}" alt="" />
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'warehouse:home_warehouse' %}" class="nav-link px-2 text-secondary">Almacen</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Ventas</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Clientes</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>