sales_admin/applications/warehouse/api/urls.py
from rest_framework import routers
from applications.warehouse.api.views import ProductCategoryViewSet, GetProductCategoryWithToken, Logout
from django.urls import path
from django.conf.urls import include

router = routers.DefaultRouter()
router.register('product-categories', ProductCategoryViewSet)
# router.register('products', ProductViewSet)

urlpatterns = [
    path("", include(router.urls), name="api-warehouse"),
    path("product-category/<int:id>/", GetProductCategoryWithToken.as_view(), name='get-product-category-token'),
    path("logout/", Logout.as_view(), name="logout")
]

sales_admin/applications/warehouse/urls.py
from django.urls import path
from . import views

app_name = "warehouse"

urlpatterns = [
    path("", views.index, name = "home_warehouse"),
    # URL para categorías de producto
    path("categorias-producto",views.product_category_list, name = "product_category_list"),
    path("categorias-producto/<int:product_category_id>",views.detail, name = "product_category_detail"),
    path("categorias-producto/nuevo", views.new, name="product_category_new"),
    path("categorias-producto/buscar", views.search,name="product_category_search"),
    path("categorias-producto/guardar", views.save, name="product_category_save")
]

sales_admin/sales_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('almacen/', include("applications.warehouse.urls")),
    path('api/warehouse/', include("applications.warehouse.api.urls")),
    path('api/login/', views.obtain_auth_token)
]

sales_admin/applications/warehouse/models.py
"""
En el archivo models.py agregamos los modelos que utilizará nuestra aplicación.
Los modelos de esta aplicación pueden ser utilizados desde otras aplicaciones.
"""
# Importamos la clase models del módulo django.db
# Link: https://docs.djangoproject.com/en/4.1/topics/db/models/
from django.db import models

# Importamos las clases MinValueValidator, MaxValueValidator para agregar validaciones
# al atributo "percent_discount"
# Link: https://docs.djangoproject.com/en/4.1/ref/validators/#module-django.core.validators
from django.core.validators import MinValueValidator, MaxValueValidator

# Importamos la clase Currency de la aplicación Sales
from applications.sales.models import Currency


class UnitMeasureCategory(models.Model):
    """
    Clase de Categoría de Unidades de Medida.

    Ejemplo: Peso, Volumen, Longitud
    """

    # Atributo "id" => columna "id" de la tabla
    # Identificador de registro de nuestra tabla.
    id = models.AutoField(primary_key=True, db_column="id")

    # Atributo "code" => columna "code" de la tabla
    # Con el parámetro unique=True, le indicamos a Django que agregue un indice
    # tipo UNIQUE a la columna "code".
    # Código de Categoría de Unidad de Medida
    code = models.CharField(max_length=3, unique=True, verbose_name="Código")

    # Atributo "name" => columna "name" de la tabla
    # Nombre de Categoría de Unidad de Medida
    name = models.CharField(max_length=30, verbose_name="Nombre")

    # Atributo "created_at" => columna "created_at" de la tabla
    # Fecha de creación de un registro
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de Creación")

    # Atributo "updated_at" => columna "updated_at" de la tabla.
    # Fecha de última modificación de un registro
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de Moficación")

    def __str__(self) -> str:
        """
        Método para devolver un string que represente al objeto
        """
        return self.name

    class Meta:
        """
        Clase Meta:
        Clase de Django para agregar opciones adicionales a nuestro modelo.
        Link: https://docs.djangoproject.com/en/4.1/ref/models/options/
        """

        # Nombre que recibirá nuestro modelo en la base de datos.
        db_table = "unit_measure_category"

        # Texto que aparecerá en nuestra aplicación.
        verbose_name = "Categoría de Unidades de Medida"


class UnitMeasure(models.Model):
    """
    Clase Unidad de Medida.

    Ejem: 
        Kg -> Categoría (Peso)
        Litro -> Categoría (Volumen), 
        g (gramo) -> Categoría (Peso) 
    """

    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=3, unique=True, verbose_name="Código")
    name = models.CharField(max_length=30, verbose_name="Nombre")

    # Atributo tipo Foreign Key (FK).
    # FK: categoría de unidad de medida
    # Le indicamos a Django que el atributo "unit_measure_category_id" se convierta en una FK
    # en nuestra base de datos.
    unit_measure_category_id = models.ForeignKey(UnitMeasureCategory, on_delete=models.CASCADE,
                                                 default=None, db_column="unit_measure_category_id", verbose_name="Categoría de Unidad de Medida")

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de Creación")

    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de Moficación")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "unit_measure"

        verbose_name = "Unidades de Medida"


class ProductCategory(models.Model):
    """
    Clase Categoría de Producto.
    Ejem: Abarrotes
    """

    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=3, unique=True, verbose_name="Código")
    name = models.CharField(max_length=50, verbose_name="Nombre")
    percent_discount = models.PositiveSmallIntegerField(default=0, validators=[
                                                        MinValueValidator(0), MaxValueValidator(50)], verbose_name="Descuento (%)")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de Creación")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de Moficación")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        #self.percent_discount = 5
        super(ProductCategory, self).save(*args, **kwargs)

    class Meta:
        db_table = "product_category"
        verbose_name = "Categoría de Producto"


class Product(models.Model):

    id = models.AutoField(primary_key=True)

    code = models.CharField(max_length=5, unique=True, verbose_name="Código")

    name = models.CharField(max_length=60, blank=False,
                            default=None, verbose_name="Nombre")

    # foreign_key: categoría de producto
    product_category_id = models.ForeignKey(ProductCategory, on_delete=models.CASCADE,
                                            default=None, db_column="product_category_id", verbose_name="Categoría Producto")

    # foreign_key: unidad de medida
    unit_measure_id = models.ForeignKey(UnitMeasure, on_delete=models.CASCADE,
                                        default=None, db_column="unit_measure_id", verbose_name="Unidad de Medida")

    # foreign_key: Moneda
    currency_id = models.ForeignKey(
        Currency, on_delete=models.CASCADE, default=None, db_column="currency_id", verbose_name="Moneda")

    # precio de compra.
    purchase_price = models.DecimalField(
        max_digits=7, decimal_places=2, default=0, verbose_name="Precio de Compra")

    # precio de venta base
    base_sale_price = models.DecimalField(
        max_digits=7, decimal_places=2, default=0, verbose_name="Precio de Venta Base")

    # require: from django.core.validators
    percent_discount = models.PositiveSmallIntegerField(default=0, validators=[
                                                        MinValueValidator(0), MaxValueValidator(60)], verbose_name="Descuento (%)")

    discount_amount = models.DecimalField(
        max_digits=7, decimal_places=2, default=0, verbose_name="Monto Descuento")

    # precio de venta
    sale_price = models.DecimalField(
        max_digits=7, decimal_places=2, default=0, verbose_name="Precio de Venta")

    # stock: PositiveIntegerField
    stock = models.PositiveIntegerField(default=0, verbose_name="Stock")

    # Activo: BooleanField
    active = models.BooleanField(default=True, verbose_name="Activo")

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha Creación")

    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Fecha Modificación")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """
        Sobre escribimos el método save de la clase Model.
        """
        # Calculamos el monto de descuento
        self.discount_amount = round(
            (int(self.percent_discount)/100)*float(self.base_sale_price), 2)
        
        # Calculamos el precio de venta
        self.sale_price = float(self.base_sale_price) - \
            float(abs(self.discount_amount))
        
        # Guardamos información del modelo
        super(Product, self).save(*args, **kwargs)

    class Meta:
        db_table = "product"
        verbose_name = "Producto"

sales_admin/applications/warehouse/forms.py
from django import forms
from .models import ProductCategory

class ProductCategoryForm(forms.ModelForm):
    """
    Formulario para el Modelo ProductCategory.

    Creamos formulario con tres inputs.
    """

    code = forms.CharField(
        #label = "Código Cat",
        label=ProductCategory._meta.get_field('code').verbose_name,
        max_length= ProductCategory._meta.get_field('code').max_length,
        help_text=('Escriba el código de categoría'),
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'code', 'placeholder': 'Código'}))

    name = forms.CharField(
        label=ProductCategory._meta.get_field('name').verbose_name,
        max_length=ProductCategory._meta.get_field('name').max_length,
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'name'}))

    percent_discount = forms.CharField(
        required=True,
        label=ProductCategory._meta.get_field('percent_discount').verbose_name,
        max_length=ProductCategory._meta.get_field('percent_discount').max_length,
        widget=forms.NumberInput(attrs={'min':0, 'max':10, 'class': 'form-control', 'id': 'percent_discount'}))

    class Meta:
        model = ProductCategory
        fields = "__all__"

sales_admin/applications/warehouse/api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.views import APIView
from applications.warehouse.models import ProductCategory
from applications.warehouse.api.serializers import ProductCategorySerializer
from rest_framework.permissions import IsAuthenticated
from django.http import JsonResponse

from rest_framework.response import Response
from rest_framework import status

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters

class ProductCategoryViewSet(ModelViewSet):
    """
    Clase ViewSet de Product Category
    """

    # Obtenemos los datos que queremos devolver.
    queryset = ProductCategory.objects.all()

    # Le indicamos el serializer que debe utilizar para convertir los objetos a JSON.
    serializer_class = ProductCategorySerializer

    # Configuración para que el VIEW sea utilizado por usuarios autenticados.
    #permission_classes = [IsAuthenticated]

    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['percent_discount']

    search_fields = ['name']

    ordering_fields = ['id', 'percent_discount']

class GetProductCategoryWithToken(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None, id = 0, *args, **kwargs):
        product_category = None

        req_user = request._user
        #print(req_user)
        have_permission = False
        if req_user.has_perm('warehouse.view_productcategory'):
            have_permission = True
            try:
                product_category = ProductCategory.objects.get(id=id)
            except ProductCategory.DoesNotExist:
                pass
        
        product_category_serializer = ProductCategorySerializer(
            product_category
        )

        payload = {
            'product_category': product_category_serializer.data,
            'have_permission': have_permission
        }

        return JsonResponse(payload)


class Logout(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None, *args, **kwargs):
        request.user.auth_token.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

sales_admin/applications/warehouse/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from applications.warehouse.models import ProductCategory
from django.views.decorators.csrf import csrf_protect
from applications.warehouse.forms import ProductCategoryForm
from django.http import HttpResponse

# Create your views here.

def index(request):
    """
    Vista Basada en Función.
    Función que devuelve página home del módulo de almacén.
    """
    return render(request, 'warehouse/index.html')

def product_category_list(request):
    """
    Función que devolverá la lista de categorías.
    Vista basada en función.
    """
    # link: https://docs.djangoproject.com/en/4.1/topics/db/queries/

    # Obtenemos los registros de la tabla product_category
    product_category_list = ProductCategory.objects.all().order_by('-id')

    # render(request, 'template.html',variables)
    return render(request, 'warehouse/product_category/list.html', {
        'product_category_list': product_category_list
    })


def detail(request, product_category_id):
    product_category = get_object_or_404(
        ProductCategory, pk=int(product_category_id))
    return render(request, "warehouse/product_category/detail.html", {
        "product_category": product_category
    })


def new(request):
    """
    Función que devuelve el formulario para agregar una nueva categoría de producto
    """
    form = ProductCategoryForm()
    return render(request, "warehouse/product_category/new.html", {
        'form': form
    })


def search(request):
    """
    Función para devolver template de búsqueda de categoría de producto.
    """
    return render(request, "warehouse/product_category/search.html", {})


@require_http_methods(["POST"])
@csrf_protect
def save(request):
    """
    Función para registrar los datos del formulario en la base de datos.
    """
    #print(request.POST)
    form = ProductCategoryForm(request.POST)
    if form.is_valid():
        try:
            # Alternativa 1
            code = form.cleaned_data.get('code')
            name = form.cleaned_data.get('name')
            percent_discount = int(form.cleaned_data.get('percent_discount'))
            pc = ProductCategory(code=code, name=name,percent_discount=percent_discount)
            pc.save()

            # Alternativa 2
            #form.save()

            return render(request, 'warehouse/product_category/new.html', {'form': form})
            # return HttpResponse("Categoría creada con éxito")
        except Exception as e:
            return HttpResponse(e)
    else:
        print(form.errors)
        return render(request, 'warehouse/product_category/new.html', {'form': form})

sales_admin/applications/warehouse/templates/warehouse/product_category/detail.html
<h1>{{product_category.name}}</h1>

sales_admin/applications/warehouse/templates/warehouse/product_category/list.html
{% extends 'base.html' %}

{% block content %}
    {% if product_category_list %}
    <h1 class="mt-5">Listado de Categorías de Producto</h1>
    <ul class="mt-4 list-group">
        {% for product_category in product_category_list %}
            <li class="list-group-item">
                <a href="{% url 'warehouse:product_category_detail' product_category.id %}">
                    {{ product_category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'warehouse:product_category_new' %}" class="btn btn-success mt-5"> Nuevo</a>
    {% endif %}
{% endblock %}

sales_admin/applications/warehouse/templates/warehouse/product_category/new.html
{% extends "base.html" %}
{% block content %}
        <div class="row mt-5">
            <div class="col-md-6 col-lg-6">

                <h1>Nueva Categoría de Producto</h1>

                <form class="post-form" action="{% url 'warehouse:product_category_save' %}" method="POST">
                {% csrf_token %}

                {% for field in form %}
                    <p>{{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                      <small class="text-muted">{{ field.help_text | safe }}</small>
                    {% endif %}
                    
                    {% for error in field.errors %}
                        <p class="text-danger">{{ error | safe }}</p>
                    {% endfor %}
                    </p>
                {% endfor %}

                <button type="submit" class="save btn btn-primary">Guardar</button> 
                <a href="{%url 'warehouse:product_category_list' %}" class="btn btn-danger"> Regresar</a>
                </form>
            </div>
        </div>
{% endblock %}

sales_admin/applications/warehouse/templates/warehouse/product_category/search.html
{% extends "base.html" %}
{% block content %}
    <div class="row mt-5">
        <div class="col-md-6 col-lg-6">
            <h2>Buscar</h2>
            <p class="mt-4">
            <input type="text" class="form-control" id="search_id" maxlength="5" style="width: 60%;" placeholder="Ingrese un ID de categoría de producto" />
            <button id="btn-search" class="btn btn-info mt-3">Buscar</button>
            </p>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-6 col-lg-6">
            <div id="output"></div>
        </div>
    </div>

    <script>
        document.getElementById("btn-search").addEventListener("click", function(event) {
            event.preventDefault();

            const $inputId = document.getElementById("search_id");
            const id = Math.abs(parseInt($inputId.value));
            const $containerOutput = document.getElementById("output");

            if (Number.isInteger(id) && id>0) {

                const URL_API = "http://localhost:8000/api";

                const endpoint = `${URL_API}/warehouse/product-categories/${id}`;

                fetch(endpoint, {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json'
                    }
                }).then(async(api_response) => {
                    const response = await api_response;
                    //console.log(response);
                    if (response.status === 404) {
                        $containerOutput.innerHTML = "No se encontraron registros.";
                    }
                    if (response.status === 200) {
                        return response.json();
                    }
                    return undefined;
                })
                .then(async(body_response) => {
                    const data = await body_response;
                    if (data !== undefined) {
                        output = `
                        <h2>Categoría de Producto</h2>
                        <ul class="list-group mb-3 mt-4">
                            <li class="list-group-item">Código: ${data.code}</li>
                            <li class="list-group-item">Nombre: ${data.name}</li>
                            <li class="list-group-item">Descuento: ${data.percent_discount} %</li>
                        </ul>
                        `
                        $containerOutput.innerHTML = output;
                    }
                })
                .catch((error) => {
                    console.log(`Error en la obtención de datos: ${error}`);
                    $containerOutput.innerHTML = "Error en la obtención de datos";
                });

            } else {
                $inputId.value = "";
                $inputId.focus();
            }
        });
    </script>

{% endblock %}